"""Procedural sound for Reachy Mini — a tiny synth for semantic-free utterances.

The audio twin of :mod:`reachy_motion.anim`. A sound is a declarative **spec** (JSON-serializable):
a *voice* (timbre) + a timeline of pitch-glide *tones* (reusing anim's easing curves) + vibrato.
``bake()`` synthesizes it to a mono float buffer at ``sr``; ``save_wav()`` writes a .wav the robot
plays through :mod:`reachy_motion.audio` (direct ALSA). Because the spec is plain data, the same
sounds can be authored in code, edited in the UI, saved, round-tripped — and later generated by an
LLM/model (the canonical-schema keystone, now for sound).

Reachy's library voice (measured -> ``sound_fingerprints.json``): pitched non-verbal "boops/warbles",
f0 ~140-900 Hz with wide glides, formant brightness ~1.2-2 kHz, some rasp. This synth targets that:
a harmonic (sawtooth-ish) source at the glided f0, shaped by resonant formants, with vibrato + a
little noise — the standard recipe for expressive non-verbal robot sound.
"""

from __future__ import annotations

import json
import wave
from dataclasses import asdict, dataclass, field
from pathlib import Path

import numpy as np

from .anim import EASES, _smooth  # share the easing vocabulary with motion

SR = 44100


@dataclass
class Voice:
    """The robot's timbre — shared across sounds like anim's pose palette is shared."""
    harmonics: int = 8            # sawtooth-ish richness (number of harmonics)
    tilt: float = 1.0             # spectral tilt: harmonic k amplitude = 1/k**tilt
    formants: tuple = (760.0, 1500.0)   # resonant formant centres (Hz) -> a vowel-ish "voice"
    formant_q: float = 5.0
    rasp: float = 0.0             # 0..1 breathy noise mixed in (raspy emotions)
    vib_rate: float = 6.0         # default vibrato rate (Hz)
    vib_depth: float = 0.015      # default vibrato depth (fraction of f0)


@dataclass
class Sound:
    """Fluent builder (mirrors :class:`anim.Anim`): chain ``.tone()`` / ``.rest()`` glides."""
    sr: int = SR
    voice: Voice = field(default_factory=Voice)
    _segs: list = field(default_factory=list)
    _f0: float = 0.0

    def tone(self, f0, dur, ease="smooth", amp=1.0, vib=None, rasp=None):
        """Glide from the previous f0 to ``f0`` over ``dur`` seconds (eased), at ``amp``."""
        vr, vd = vib if vib is not None else (self.voice.vib_rate, self.voice.vib_depth)
        self._segs.append({"f0": float(f0), "dur": max(1e-3, float(dur)), "ease": ease,
                           "amp": float(amp), "vib_rate": vr, "vib_depth": vd,
                           "rasp": self.voice.rasp if rasp is None else float(rasp)})
        self._f0 = float(f0)
        return self

    def rest(self, dur):
        """A silent gap (fades out, then the next tone fades in)."""
        self._segs.append({"f0": self._f0 or 1.0, "dur": max(1e-3, float(dur)), "ease": "linear",
                           "amp": 0.0, "vib_rate": 0.0, "vib_depth": 0.0, "rasp": 0.0})
        return self

    def spec(self) -> dict:
        return {"sr": self.sr, "voice": asdict(self.voice), "segments": list(self._segs)}

    def bake(self) -> np.ndarray:
        return bake_spec(self.spec())

    def save_wav(self, path) -> str:
        save_wav(self.bake(), self.sr, path)
        return str(path)


def from_spec(spec: dict) -> Sound:
    s = Sound(sr=int(spec.get("sr", SR)), voice=Voice(**spec.get("voice", {})))
    s._segs = [dict(seg) for seg in spec.get("segments", [])]
    if s._segs:
        s._f0 = s._segs[-1]["f0"]
    return s


def _formant(x, sr, fc, q):
    """Resonant peak (formant emphasis) at ``fc``. Manual biquad peaking filter (no scipy dep)."""
    w0 = 2 * np.pi * min(fc, sr * 0.45) / sr
    A = 3.2                                  # peak gain
    alpha = np.sin(w0) / (2 * q)
    b0 = 1 + alpha * A; b1 = -2 * np.cos(w0); b2 = 1 - alpha * A
    a0 = 1 + alpha / A; a1 = -2 * np.cos(w0); a2 = 1 - alpha / A
    b = np.array([b0, b1, b2]) / a0
    a = np.array([1.0, a1 / a0, a2 / a0])
    y = np.zeros_like(x)
    x1 = x2 = y1 = y2 = 0.0
    for i in range(len(x)):
        y[i] = b[0] * x[i] + b[1] * x1 + b[2] * x2 - a[1] * y1 - a[2] * y2
        x2, x1 = x1, x[i]; y2, y1 = y1, y[i]
    return y


def bake_spec(spec: dict) -> np.ndarray:
    """Synthesize a sound spec into a mono float32 buffer in [-1, 1]."""
    sr = int(spec.get("sr", SR))
    v = spec.get("voice", {})
    harmonics = int(v.get("harmonics", 8)); tilt = float(v.get("tilt", 1.0))
    formants = v.get("formants", (760.0, 1500.0)); fq = float(v.get("formant_q", 5.0))
    segs = spec.get("segments", [])
    if not segs:
        return np.zeros(1, np.float32)
    # per-sample f0 / amp / vibrato by eased interpolation between tone keyframes (like anim._sample)
    f0c, ampc, vrc, vdc, rac = [], [], [], [], []
    pf, pa = segs[0]["f0"], 0.0
    for s in segs:
        n = max(1, int(round(s["dur"] * sr)))
        e = EASES.get(s["ease"], _smooth)
        u = np.array([e(i / n) for i in range(n)])
        f0c.append(pf + (s["f0"] - pf) * u)
        ampc.append(pa + (s["amp"] - pa) * u)
        vrc.append(np.full(n, s.get("vib_rate", 0.0)))
        vdc.append(np.full(n, s.get("vib_depth", 0.0)))
        rac.append(np.full(n, s.get("rasp", 0.0)))
        pf, pa = s["f0"], s["amp"]
    f0 = np.concatenate(f0c); amp = np.concatenate(ampc)
    vr = np.concatenate(vrc); vd = np.concatenate(vdc); rasp = np.concatenate(rac)
    t = np.arange(len(f0)) / sr
    f0 = f0 * (1.0 + vd * np.sin(2 * np.pi * vr * t))     # vibrato
    phase = 2 * np.pi * np.cumsum(f0) / sr
    sig = np.zeros(len(phase))                            # sawtooth-ish source
    for k in range(1, harmonics + 1):
        sig += (1.0 / (k ** tilt)) * np.sin(k * phase)
    sig /= max(1e-9, np.abs(sig).max())
    if formants:                                          # formant shaping (the "voice")
        fsum = sum(_formant(sig, sr, float(fc), fq) for fc in formants) / len(formants)
        sig = 0.5 * sig + 0.9 * fsum
    if rasp.max() > 0:                                    # raspy/breathy texture
        rng = np.random.default_rng(0)
        sig = sig + rasp * 0.5 * _formant(rng.standard_normal(len(sig)), sr, 2600, 1.2)
    env = amp.copy()                                      # amplitude env + click-free ends
    a = int(0.006 * sr)
    if a > 0 and len(env) > 2 * a:
        env[:a] *= np.linspace(0, 1, a); env[-a:] *= np.linspace(1, 0, a)
    sig *= env
    sig /= max(1e-9, np.abs(sig).max())
    return (0.9 * sig).astype(np.float32)


def save_wav(samples: np.ndarray, sr: int, path) -> None:
    pcm = (np.clip(samples, -1.0, 1.0) * 32767.0).astype("<i2")
    with wave.open(str(path), "wb") as w:
        w.setnchannels(1); w.setsampwidth(2); w.setframerate(int(sr)); w.writeframes(pcm.tobytes())


# ---- code-authored presets (tuned from sound_fingerprints.json), paired with the anim BUILTINS ----

def _curious() -> Sound:        # questioning wander, mid-high — pairs with curious_look
    return (Sound().tone(500, 0.16, "ease_out").tone(770, 0.22, "back").tone(560, 0.18, "smooth")
            .tone(700, 0.20, "ease_out").tone(690, 0.18, "smooth"))

def _cheerful() -> Sound:       # bright bouncy rise — pairs with happy_bounce
    return (Sound(voice=Voice(formants=(820, 1700), vib_depth=0.02))
            .tone(560, 0.10, "ease_out").tone(800, 0.12, "back").tone(700, 0.08, "smooth")
            .tone(840, 0.16, "back").tone(800, 0.14, "ease_out"))

def _greeting() -> Sound:       # friendly hello bloop-up — pairs with greeting
    return (Sound().tone(520, 0.10, "ease_out").tone(720, 0.14, "back").rest(0.05)
            .tone(640, 0.10).tone(820, 0.16, "back"))

def _yes() -> Sound:            # affirmative settle down — pairs with yes_nod
    return (Sound().tone(560, 0.12, "ease_out").tone(440, 0.16, "smooth").tone(300, 0.22, "ease_in"))

def _no() -> Sound:             # sharp uh-uh — pairs with no_shake
    return (Sound(voice=Voice(formants=(700, 2000)))
            .tone(800, 0.10, "back").tone(420, 0.08, "ease_in").rest(0.04)
            .tone(800, 0.12, "back").tone(380, 0.10, "ease_in"))

def _alert() -> Sound:          # quick rising ping — pairs with alert
    return (Sound(voice=Voice(formants=(900, 1900)))
            .tone(520, 0.06, "ease_out").tone(880, 0.14, "back").tone(760, 0.12, "smooth"))

def _surprised() -> Sound:      # fast leap up then fall — pairs with amazed/surprised
    return (Sound(voice=Voice(vib_depth=0.025))
            .tone(450, 0.06, "ease_out").tone(860, 0.16, "back").tone(640, 0.18, "ease_in"))

def _sad() -> Sound:            # falling whine, slow, trembly — pairs with sleepy/sad
    return (Sound(voice=Voice(vib_rate=5.0, vib_depth=0.03, formants=(620, 1300)))
            .tone(540, 0.25, "ease_out").tone(360, 0.40, "ease_in").tone(280, 0.55, "smooth"))

def _scared() -> Sound:         # trembly high flinch — pairs with scared
    return (Sound(voice=Voice(vib_rate=9.0, vib_depth=0.04, formants=(800, 1900), rasp=0.15))
            .tone(840, 0.10, "ease_out").tone(560, 0.18, "ease_in").tone(820, 0.22, "back"))

def _sleepy() -> Sound:         # slow descending yawn, soft — pairs with sleepy
    return (Sound(voice=Voice(formants=(600, 1200), vib_depth=0.01))
            .tone(560, 0.35, "ease_out", amp=0.7).tone(420, 0.55, "ease_in", amp=0.8)
            .tone(360, 0.6, "smooth", amp=0.5))

def _laughing() -> Sound:       # bouncy hehe — pairs with laughing
    s = Sound(voice=Voice(formants=(850, 1600)))
    for f in (760, 800, 740, 810, 760):
        s.tone(f, 0.07, "back").tone(f - 120, 0.06, "ease_in")
    return s


BUILTINS = {
    "curious": _curious, "cheerful": _cheerful, "greeting": _greeting, "yes": _yes, "no": _no,
    "alert": _alert, "surprised": _surprised, "sad": _sad, "scared": _scared,
    "sleepy": _sleepy, "laughing": _laughing,
}


def builtin_specs() -> dict:
    return {name: fn().spec() for name, fn in BUILTINS.items()}


# ---- the fitted library: 57 emotions derived from the real WAVs (scripts/fit_sounds.py) ----
def _load_library() -> dict:
    f = Path(__file__).with_name("fitted_sounds.json")
    try:
        return json.loads(f.read_text())
    except Exception:  # noqa: BLE001
        return {}


LIBRARY = _load_library()          # {emotion: spec} — data-grounded melodies + voices


def names() -> list:
    """All playable sound names (fitted library first, then any hand presets not in it)."""
    return sorted(LIBRARY) + [n for n in BUILTINS if n not in LIBRARY]


def get(name: str) -> Sound:
    """A Sound by name — prefers the data-fitted library, falls back to the hand presets."""
    if name in LIBRARY:
        return from_spec(LIBRARY[name])
    return BUILTINS[name]()


def save_to_library(name: str, spec: dict) -> None:
    """Persist an (edited) spec into the library JSON so it survives + shows in the dropdown."""
    LIBRARY[name] = spec
    Path(__file__).with_name("fitted_sounds.json").write_text(json.dumps(LIBRARY, indent=1))


if __name__ == "__main__":
    # Tuning CLI:  python -m reachy_motion.sound            -> play every preset
    #              python -m reachy_motion.sound curious     -> play one (re-run after editing it)
    #              python -m reachy_motion.sound yes sad      -> play several
    #              python -m reachy_motion.sound all --loop   -> loop the lot
    #              add --no-play to only write the .wav files to /tmp
    import sys
    import time

    flags = [a for a in sys.argv[1:] if a.startswith("-")]
    args = [a for a in sys.argv[1:] if not a.startswith("-")]
    allnames = names()
    picked = allnames if (not args or args[0] == "all") else args
    bad = [n for n in picked if n not in allnames]
    if bad:
        print(f"unknown: {bad}\navailable: {', '.join(allnames)}"); sys.exit(1)
    play = "--no-play" not in flags
    audio = None
    if play:
        from . import audio  # noqa: F811
    while True:
        for name in picked:
            out = Path("/tmp") / f"reachy_sound_{name}.wav"
            get(name).save_wav(out)
            print(f"♪ {name}  ({out})")
            if play:
                try:
                    audio.play_wav(out, blocking=True)
                except Exception as e:  # noqa: BLE001
                    print(f"  (couldn't play — {e})"); sys.exit(1)
                time.sleep(0.3)
        if "--loop" not in flags:
            break
